### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [atsushi130/EnigmaMachine#3]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by atsushi130** [comment]
Hi @dtolnay,
Thank you for letting me know. I did not know that announcement.
I make use another library instead of rustc-serialze.
